spring:
  application:
    name: payment-service
  config:
    import:
      optional:configserver:http://localhost:8888
  kafka:
    consumer:
      group-id: payment-group
    bootstrap-servers: localhost:9092
server:
  port: 8089