services:
  postgres:
    image: postgres:16
    container_name: local-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: beaver-user-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      TZ: UTC
      PGTZ : UTC
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres-data:
