spring:
  application:
    name: config-service
  cloud:
    config:
      uri: http://localhost:8888
      label: master
      fail-fast: true
      server:
        git:
          uri: https://github.com/karlien2918/bearver-config-repo.git
          #username: ${CONFIG_USERNAME}
          #password: ${CONFIG_PASSWORD}
server:
  port: 8888