spring:
  application:
    name: infra-postgresdb
  datasource:
    url: jdbc:postgresql://localhost:5432/beaver-user-db
    username: admin
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
