name: CI - Beaver Docker Build

on:
  push:
    branches:
      - 'dev'  # 모든 브랜치에 push 이벤트 발생 시 실행됨 (예: feature/로그인, dev 등)

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Show working directory
        run: pwd

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io                         # 사용할 레지스트리 주소 (GitHub Container Registry)
          username: ${{ github.actor }}             # 현재 GitHub Actions 실행 주체 (보통 커밋 푸시한 유저)
          password: ${{ secrets.GITHUB_TOKEN }}     # GitHub가 자동으로 제공하는 권한 토큰 – 별도 설정 불필요

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:ci-${{ github.sha }}
