name: Deploy K8s Module

on:
  workflow_dispatch:
    inputs:
      module:
        description: '배포할 모듈 선택'
        required: true
        type: choice
        options:
          - user-service
          - payment-service

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - name: Set selected module as matrix
        id: set
        run: |
          echo "matrix={\"module\":[\"${{ github.event.inputs.module }}\"]}" >> $GITHUB_OUTPUT

  deploy:
    needs: set-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy selected module
        run: |
          echo "Deploying ${{ matrix.module }}"
          git add k8s/${{ matrix.module }}-deployment.yaml
